name = "backend"
compatibility_date = "2024-08-01"

 [vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDRkMTA2ZWYtNWIzZi00MDIyLTg4NTAtYjEwNmZhNmZhMjBkIiwidGVuYW50X2lkIjoiY2ZiZGU5YjkzYjUyMDhkMDE2ZTUxM2ZjMzJmY2M4ZjgwMDU0NDlkMWVlNmM2ZjJmMGU3OTVlMDNjMGFlYTM3NCIsImludGVybmFsX3NlY3JldCI6ImE4NjJlOTI0LTM3MGUtNGM1OS05Mzk4LTEyOTBlZDAxYWM5MSJ9.dQp8LREZrxxFgiftDrK5G6ZifVa-QP7tukZES_ryzg8"
 JWT_SECRET = "Mayank123"